#!/bin/bash

export AWS_SDK_CPP_VER_MAJOR="1"
export AWS_SDK_CPP_VER_MINOR="4"
export AWS_SDK_CPP_VER_PATCH="50"
export AWS_SDK_CPP_VERSION="${AWS_SDK_CPP_VER_MAJOR}.${AWS_SDK_CPP_VER_MINOR}.${AWS_SDK_CPP_VER_PATCH}"

